---
all:
  vars:
    # GKE cluster variables
    gcp_project: ascn-440717  # ID of GCP Project
    gcp_auth_kind: serviceaccount # Do not change
    gcp_cred_file: ./gcp-key.json # Path to service account keys (json file downloaded from GCP)

    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    #gcp_machine_type: e2-small        # 2 vCPUs 2GB RAM. Can be changed if necessary
    gcp_machine_type: e2-standard-2   # 2 vCPUs 8GB RAM.
    #gcp_machine_type: e2-standard-4   # 4 vCPUs 16GB RAM.
    #gcp_machine_type: e2-highcpu-4    # 4 vCPUs 4GB RAM.
    gcp_disk_size_gb: 100 # Can be changed if necessary
    gcp_initial_node_count: 3 # Number of nodes to create. Can be changed if necessary

    # BEGIN Test variables (DO NOT CHANGE)
    app_notifier_email: notifier@moonshot.pt
    app_notifier_password: 123456
    result_code: 200
    dgc_uvci:
    # END Test variables (DO NOT CHANGE)

    # APP variables
    app_ip: <APP_SERVICE_IP>
    app_port: <APP_SERVICE_PORT> 
    app_protocol: http
    
    # Additional variables
    cluster_name: ascn-cluster