apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: jmeter
    app.kubernetes.io/instance: {{ service_name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: ansible