apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moonshot-hpa
  namespace: {{ namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ moonshot_deployment_name }}
  minReplicas: {{ hpa_min_replicas }}
  maxReplicas: {{ hpa_max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ hpa_target_cpu_utilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ hpa_target_memory_utilization }}
