apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ db_deployment_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ db_deployment_name }}
    app.kubernetes.io/version: "13.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: postgres-system
    app.kubernetes.io/managed-by: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: {{ db_deployment_name }}
    spec:
      containers:
        - name: postgres
          image: {{ db_image }}
          ports:
            - containerPort: {{ db_port }}
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ db_pvc_name }}
