apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ db_pv_name }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ db_pv_name }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: ansible
spec:
  capacity:
    storage: {{ pv_storage_size }}
  accessModes:
    - {{ pv_access_mode }}
  hostPath:
    path: "/mnt/data/postgres"